### ISSUE TITLE
Ponzi: Fantom One Profit

### ISSUE THREAD

**Issue by mculp** [tintinweb/smart-contract-sanctuary-fantom#1]
I didn't know where else to put this, but [this one's definitely a straight ponzi](https://github.com/tintinweb/smart-contract-sanctuary-fantom/blob/b945664bc27febb161ed8f16bffd3e8c419245ac/contracts/mainnet/3b/3b3ba861827A7444DA0a665ae47F636fE142Ff81_FantomOneProfit.sol#L88-L91)

I [wrote about it a bit](https://twitter.com/_mculp/status/1503431049698848772?s=20) on Twitter.

[Another instance of this contract I found on GitHub is this.](https://github.com/kennethshso/scalerts/commit/b91ba4c9a28dc2d9c5b0362109e5ca15526eb5a6) From what I can tell, it looks like he's copying scam contracts and this repo is an aggregator to keep up with how much money he's making. Why's it public? :joy:

original: https://www.fantomoneprofit.io/#/
@kennethshso copy: https://fantomoneprofit.site/

**Comment by kennethshso** [comment]
Haha, I'm not an author or copier of any contract. I'm just a small investor who write a simple utility to keep track the balance of some contracts in order to look for some investment opportunity. Any comment is welcome!
